<a href="https://colab.research.google.com/github/sriharikrishna/EuroAD26/blob/main/EuroAD_tf_odetest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import tensorflow_probability as tfp
import tensorflow as tf

y0 = tf.Variable([2.0 , 6.], shape=(2,), dtype=tf.float64)
t_i, t_m, t_f = 0., 0.5, 1.
A = tf.Variable([[2., 4.], [3., 2.]], dtype = tf.float64)

def ode_fn(_: float, y: tf.Tensor, A: tf.Tensor) -> tf.Tensor:
    val = tf.linalg.matvec(A, y)
    return val

with tf.GradientTape(persistent=True) as tape:
    tape.watch(y0)
    resultsfull = tfp.math.ode.DormandPrince().solve(ode_fn, t_i, y0,
                              solution_times = tfp.math.ode.ChosenBySolver(final_time=t_f),
                              #solution_times = [t_m, t_f],
                              constants={"A": A})
print(resultsfull.states[-1])
jac = tape.jacobian(resultsfull.states, y0, experimental_use_pfor=False)
print(jac)

tf.Tensor([1046.67867417  907.43744811], shape=(2,), dtype=float64)
tf.Tensor(
[[[1.00000000e+00 0.00000000e+00]
  [0.00000000e+00 1.00000000e+00]]

 [[1.00200801e+00 4.00801611e-03]
  [3.00601208e-03 1.00200801e+00]]

 [[1.02298602e+00 4.49896132e-02]
  [3.37422099e-02 1.02298602e+00]]

 [[1.34201738e+00 5.68129155e-01]
  [4.26096866e-01 1.34201738e+00]]

 [[7.27529824e+00 7.83208782e+00]
  [5.87406583e+00 7.27529820e+00]]

 [[4.47490341e+01 5.13250973e+01]
  [3.84938230e+01 4.47490341e+01]]

 [[1.18149316e+02 1.36160013e+02]
  [1.02120010e+02 1.18149316e+02]]], shape=(7, 2, 2), dtype=float64)


In [25]:
import tensorflow_probability as tfp
import tensorflow as tf

y0 = tf.Variable([2.0 , 6.], shape=(2,), dtype=tf.complex128)
t_i, t_m, t_f = 0., 0.5, 1.
A = tf.Variable([[2., 4.], [3., 2.]], dtype = tf.complex128)

def ode_fn(_: float, y: tf.Tensor, A: tf.Tensor) -> tf.Tensor:
    val = tf.linalg.matvec(A, y)
    return val

with tf.GradientTape(persistent=True) as tape:
    tape.watch(y0)
    resultsfull = tfp.math.ode.DormandPrince().solve(ode_fn, t_i, y0,
                              solution_times = tfp.math.ode.ChosenBySolver(final_time=t_f),
                              #solution_times = [t_m, t_f],
                              constants={"A": A})
print(resultsfull.states[-1])
jac = tape.jacobian(resultsfull.states, y0, experimental_use_pfor=False)
print(jac)

tf.Tensor([1046.67867417+0.j  907.43744811+0.j], shape=(2,), dtype=complex128)


NotImplementedError: ignored